### ISSUE TITLE
Duplicate ID for different players

### ISSUE THREAD

**Issue by Youfoundme001** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#14]
Greetings,

While running the listallblocks command and exporting the data to a CSV, I noticed that a few players had duplicate IDs when I combined multiple servers.  Is the ID generated by your plugin, or is it the Keen Player ID?  Is this due to being different servers?  Below is an example:

Server 1:  "144115188075856522","PLAYERONE","KLR","SurvivalKit8x","1","140"
Server 2: "144115188075856522","PLAYERTWO","FEN","Antenna","1","100"

**Comment by LordTylus** [comment]
This is the Keen IdentityID. 

These IDs are only unique per world. So multiple worlds will use the same IDs. Some of the server cluster Plugins, when using stuff like jump gates try to deal with that by changing Identity IDs of players across worlds to keep them in sync. Not sure how they do it.

You may have noticed before when you take a blueprint from Server A and paste the very same blueprint in Server B that the owner of that blueprint may be some random person, just because the ID stored in the blueprint belongs to a different player on Server B 

Additionally you may find duplicates in the same world when you start deleting identities with space master or !identity purge command, as it may happen that an ID gets reused after being deleted. You wont get the same ID twice in the same report. But it could be that when you look at a report today and compare it to one from 2 weeks ago, that the same ID is now used by a different player. 

In any case this is nothing PCU Transferrer is able to deal with as it just outputs the situation at the time the command is run and due to its single world design it cannot even anticipate that you want to combine results from different servers. So best you should do is to to keep these CSVs seperate.

**Comment by Youfoundme001** [comment]
@LordTylus Thank you so much for explaining this to me.  I appreciate the hard work and time you put into your plugins!  I've been able to create some beautiful things using your work!  

Side question (But feel free to mark this as resolved/closed) could you add Steam64ID to the listallblocks export?  Maybe I could use those to separate duplicate IDs

**Comment by LordTylus** [comment]
Feel free to create a separate issue for that request. And if I feel like it I may or may not add it at some point.
