### ISSUE TITLE
Allow non-admin users to transfer their grids to other players

### ISSUE THREAD

**Issue by ca1f** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#8]
Please allow non-admin users to use the `!transferowner` command so they can transfer their grids to other players.

Welding a grid in survival mode with the projector/merge block will cause all blocks built by that combination to be owned by the player that built these blocks. This is undesirable in a multiplayer world where different players share the same base and the same setup for building ships because they in turn can't modify thrusters for example even though these players are part of the same faction and the ownership of thrusters can't be transferred via the vanilla UI. The `!transferowner` command would be useful in that situation so that the player, who "owns" the shipyard, can also just simply transfer the ownership of that freshly built grid to the other player, who just used the shipyard to build the ship, without requiring an admin to act.

**Comment by LordTylus** [comment]
Hello,
Thank you for your report. 

I dont really see why a player would require this command. It is designed for admins to be used to transfer grids between players independent of faction and online offline state and even without being logged into the game.

If the owner of the shipyard does not want the blocks that are now owned by him he simply can open the terminal select all blocks using ctrl+a and transfer them to the desired player. Which is essentially the same as using !transferowner

Also this command does not care for who the previous owner was so essentially this command can assign. Ownership from any player to any player. This is something that has potential to mess a lot of stuff up if there is just a tiny loophole left inside

**Comment by ca1f** [comment]
> If the owner of the shipyard does not want the blocks that are now owned by him he simply can open the terminal select all blocks using ctrl+a and transfer them to the desired player. Which is essentially the same as using !transferowner

Except this doesn't work for thruster blocks in example. Their ownership can't be transferred at all via the control panel. Players other than the original builder can't change the grid name at all either, which is by design a good thing actually but problematic if you want to "hand over" a ship. So this is where this plugin comes handy in the moment for me. Players tell me they want to transfer grid X to Player Y and I assign it to them after checking. I would love to empower players to transfer grid ownership between them without me having to resort to the server console though.

**Comment by LordTylus** [comment]
Thrusters are unownable blocks they can Only be accessed from the player that has the majority of the ownable blocks on the grid.

You can simply verify that with a grid that has a 1 battery and 1 thruster. The one that owns the battery has access to the thruster. And is also the one that can rename the grid.

Renaming grids is not tied to the player that originally build the grid but to the one owning the majority. Since players can solve any ownership related issues themselves i dont see a need for a plugin update.

**Comment by LordTylus** [comment]
Only other thing that could interfere with ownership could be mods or other plugins. For example the block limiter plugin has settings to prevent ownership changes. The solution then would be to configure those correctly.

It could btw be possible for a mod to remove the access restrictions for thrusters I would be surprised if there is none that could do that yet.

**Comment by ca1f** [comment]
So, we just had a case where Player A contributed some Yield Modules to a refinery, that sits on a grid owned Player B, and these yield modules can't be assigned an owner either to transfer ownership, yet these modules still appeared in the grid info screen of Player A and Player A was able to remove these blocks through that interface. 

I still think it would be really helpful, if players could use that command to transfer their own blocks to other player in situations like these.

**Comment by LordTylus** [comment]
Also that is a feature ingame:

There is a difference Between a Player owning a block, and a Player being author of a block:

The sole reason of authorship is to have block and pcu limits applied. It has no other purpose. If the player doesnt want the grids eating up his pcu and / or block limits he can transfer the blocks themselves:

![image](https://user-images.githubusercontent.com/22499516/87824730-18715c80-c876-11ea-9e7a-5e616ef73794.png)
there the player can Select ANY other online player. Which then gets promted with a Dialog saying "Hey Player A tries to transfer X amount of blocks to you, do you accept?"

After that player accepted you can see it when using a welder for example on the block
![image](https://user-images.githubusercontent.com/22499516/87824824-49519180-c876-11ea-9d7c-902dedbf10d5.png)

Assigning Authorship should NEVER be done without the other players consent because players can just load all their expensive grids onto an other one effectively blocking them from building any more blocks. 

this is an option admins especially when copying and pasting grids. But no player should be able to do that.

Ownership can be transferred via the Terminal itself

![image](https://user-images.githubusercontent.com/22499516/87825150-dbf23080-c876-11ea-96ef-161844fcbd95.png)
You DONT need to transfer stuff like Thrusters or Lights. Those will automatically become accessible as soon as one player owns the majority of the blocks

![image](https://user-images.githubusercontent.com/22499516/87825729-ec56db00-c877-11ea-87fa-9a8e0b39da2a.png)
after owning like half of the blocks myself

![image](https://user-images.githubusercontent.com/22499516/87825784-0c869a00-c878-11ea-97ff-4a0bc8a68851.png)

![image](https://user-images.githubusercontent.com/22499516/87825812-17412f00-c878-11ea-8485-ea62959f435d.png)

there is abolutely no need for players to have access to these commands as they can do everything they need themselves.
